sonar.projectKey=patient-system-main
sonar.projectName=patient system main
sonar.projectVersion=1.0

# Código fuente y pruebas (separados)
sonar.sources=src/main
sonar.tests=src/test

# Clases compiladas (OBLIGATORIO en Java)
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Reporte de cobertura JaCoCo (lo genera "mvn test")
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Excluir la regla S100 (nombres de métodos) SOLO en las pruebas
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*Test.java

sonar.host.url=http://localhost:9000
sonar.token=squ_254e216bd6d1069258b273084d73e88ab4b731bd
sonar.sourceEncoding=UTF-8