sonar.projectKey=patient-system-main
sonar.projectName=patient system main
sonar.projectVersion=1.0

# Java + HTML/CSS/JS: incluye código y recursos web
sonar.sources=src/main

# OBLIGATORIO en Java: ruta a las clases compiladas
sonar.java.binaries=target/classes

sonar.host.url=http://localhost:9000
sonar.token=squ_254e216bd6d1069258b273084d73e88ab4b731bd
sonar.sourceEncoding=UTF-8